name: Build and Deploy

on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Make mvnw Executable
        run: chmod +x mvnw

      - name: Build Spring Project
        run: ./mvnw clean install
      
      - name: SSH into OCI Instance and Stop old Application
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.OCI_INSTANCE_IP }}
          username: ${{ secrets.OCI_INSTANCE_USERNAME }}
          key: ${{ secrets.OCI_INSTANCE_PRIVATE_KEY }}
          script: |
            sudo systemctl stop bank-application

      - name: Delete Existing Files in OCI Instance
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.OCI_INSTANCE_IP }}
          username: ${{ secrets.OCI_INSTANCE_USERNAME }}
          key: ${{ secrets.OCI_INSTANCE_PRIVATE_KEY }}
          script: |
            rm -rf bank/app/runtime/target
            rm bank/app/runtime/bank-0.0.1-SNAPSHOT.jar
         
      - name: Copy JAR to OCI Instance
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.OCI_INSTANCE_IP }}
          username: ${{ secrets.OCI_INSTANCE_USERNAME }}
          key: ${{ secrets.OCI_INSTANCE_PRIVATE_KEY }}
          source: 'target/bank-0.0.1-SNAPSHOT.jar'
          target: 'bank/app/runtime'

      - name: SSH into OCI Instance and Run Application
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.OCI_INSTANCE_IP }}
          username: ${{ secrets.OCI_INSTANCE_USERNAME }}
          key: ${{ secrets.OCI_INSTANCE_PRIVATE_KEY }}
          script: |
            mv bank/app/runtime/target/bank-0.0.1-SNAPSHOT.jar bank/app/runtime/bank-0.0.1-SNAPSHOT.jar
            sudo systemctl start bank-application
