name: Build and Deploy

on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Make mvnw Executable
        run: chmod +x mvnw

      - name: Create External Config File
        run: |
          mkdir -p config
          echo "[DEFAULT]" >> config/bucket-config 
          echo "user=${{ secrets.OCI_USER_OCID }}" >> config/bucket-config
          echo "fingerprint=${{ secrets.OCI_API_KEY_FINGERPRINT }}" >> config/bucket-config
          echo "tenancy=${{ secrets.OCI_TENANCY_OCID }}" >> config/bucket-config
          echo "region=${{ secrets.OCI_REGION_ID }}" >> config/bucket-config
          echo "key_file=./config/key_file.pem" >> config/bucket-config
          echo "storage.bucket.namespace=${{ secrets.OCI_BUCKET_NAMESPACE }}" >> config/application.properties
          echo "storage.bucket.name=${{ secrets.OCI_BUCKET_NAME }}" >> config/application.properties
          echo "${{ secrets.API_PRIVATE_KEY }}" >> config/key_file.pem
          
      - name: Build Spring Project
        run: ./mvnw clean install

      - name: List Files for Debugging
        run: ls -la target config
      
      - name: SSH into OCI Instance and Stop old Application
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.OCI_INSTANCE_IP }}
          username: ${{ secrets.OCI_INSTANCE_USERNAME }}
          key: ${{ secrets.OCI_INSTANCE_PRIVATE_KEY }}
          script: |
            sudo systemctl stop bank-application

      - name: Delete Existing Files in OCI Instance
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.OCI_INSTANCE_IP }}
          username: ${{ secrets.OCI_INSTANCE_USERNAME }}
          key: ${{ secrets.OCI_INSTANCE_PRIVATE_KEY }}
          script: |
            rm -rf bank/app/runtime/target
            rm bank/app/runtime/bank-application.jar
            rm -rf bank/app/runtime/config
         
      - name: Copy JAR to OCI Instance
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.OCI_INSTANCE_IP }}
          username: ${{ secrets.OCI_INSTANCE_USERNAME }}
          key: ${{ secrets.OCI_INSTANCE_PRIVATE_KEY }}
          source: 'target/bank-application.jar,config/application.properties,config/bucket-config,config/key_file.pem'
          target: 'bank/app/runtime'

      - name: SSH into OCI Instance and Run Application
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.OCI_INSTANCE_IP }}
          username: ${{ secrets.OCI_INSTANCE_USERNAME }}
          key: ${{ secrets.OCI_INSTANCE_PRIVATE_KEY }}
          script: |
            mv bank/app/runtime/target/bank-application.jar bank/app/runtime/bank-application.jar
            mv bank/app/runtim/target/config bank/app/runtime/config
            sudo systemctl start bank-application
