name: 'Build and Deploy Backend to Cloud Run'

on:
  workflow_dispatch:

env:
  PROJECT_ID: '${{ secrets.gcp_project_id }}' 
  REGION: '${{ secrets.gcp_region }}' 
  SERVICE: '${{ secrets.gcp_frontend_service }}' 
  REPOSITORY: '${{ secrets.gcp_repository }}'
  SERVICE_ACCOUNT: '${{ secrets.gcp_service_account }}'
  WORKLOAD_IDENTITY_PROVIDER: '${{ secrets.gcp_wip }}'

jobs:
  deploy:
    runs-on: 'ubuntu-latest'

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@v4' # actions/checkout@v4


      # Configure Workload Identity Federation and generate an access token.
      #
      # See https://github.com/google-github-actions/auth for more options,
      # including authenticating via a JSON credentials file.
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v2' # google-github-actions/auth@v2
        with:
          service_account: '${{ env.SERVICE_ACCOUNT }}'
          workload_identity_provider: '${{ env.WORKLOAD_IDENTITY_PROVIDER }}'

      # BEGIN - Docker auth
      # If you already have a container image, you can omit these steps.

      - name: 'Docker Auth'
        run: |-
          gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev
        # docker login -u oauth2accesstoken -p "$(gcloud auth print-access-token)" https://${{ env.REGION }}-docker.pkg.dev


      - name: 'Docker Build and Push Container'
        run: |-
          DOCKER_TAG="${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.SERVICE }}:${{ github.sha }}"
          docker build --tag "${DOCKER_TAG}" -f frontend/Dockerfile frontend
          docker push "${DOCKER_TAG}"


      - name: 'Deploy to Cloud Run'
        uses: 'google-github-actions/deploy-cloudrun@v2' # google-github-actions/deploy-cloudrun@v2
        with:
          service: '${{ env.SERVICE }}'
          region: '${{ env.REGION }}'
          image: '${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.SERVICE }}:${{ github.sha }}'
          
          
      # If required, use the Cloud Run url output in later steps
      - name: Show Output
        run: echo ${{ steps.deploy.outputs.url }}