name: 'Build and Deploy All'

on:
  workflow_dispatch:

permissions:
  contents: 'read'
  id-token: 'write'


jobs:
  # Build Jobs
  deploy-backend:
    uses: ./.github/workflows/google-cloudrun-backend-docker.yml
    secrets: inherit

  deploy-gateway:
    needs: deploy-backend
    uses: ./.github/workflows/google-cloudrun-gateway-docker.yml
    secrets: inherit


  deploy-frontend:
    needs: deploy-gateway
    uses: ./.github/workflows/google-cloudrun-frontend-docker.yml
    secrets: inherit